language: c
sudo: required
dist: trusty
compiler: clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake autoconf libtool pkg-config uuid-dev
before_script:
- ( cd .. && git clone --depth=50 --branch=develop https://github.com/TaliskerPlatform/idl.git idl )
- ( cd ../idl && autoreconf -f -i && ./configure && make && sudo make install )
- autoreconf -f -i
script:
- ./configure && make && make check
