language: c
sudo: required
dist: trusty
compiler: clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake autoconf libtool pkg-config uuid-dev
before_script:
- autoreconf -f -i
script:
- ./configure && make && make check
